[package]
name = "charname"
version = "0.1.3"
edition = "2018"
authors = ["Hasan Ibraheem <hasantiny@gmail.com>"]
license = "MPL-2.0"
description = "Incredibly simple library that just gives you the Unicode name for a character."
repository = "https://github.com/JuanPotato/charname"

[dependencies]
phf = "0.8.0"

[build-dependencies]
phf_codegen = "0.8.0"
